# Generated by Django 5.0.3 on 2024-04-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag_category_icon_user_avatar_lesson_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='tag',
            new_name='tags',
        ),
    ]
